//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallongeStats.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChallongeStats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a API Key (Don&apos;t show).
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Challonge Stats.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Easanles 2018 - Version 1.1.
        /// </summary>
        internal static string AuthorVersion {
            get {
                return ResourceManager.GetString("AuthorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Challonge ID.
        /// </summary>
        internal static string ChallongeID {
            get {
                return ResourceManager.GetString("ChallongeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty {0} file generated.
        /// </summary>
        internal static string ConfigGenerated {
            get {
                return ResourceManager.GetString("ConfigGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while reading config file.
        /// </summary>
        internal static string ConfigReadError {
            get {
                return ResourceManager.GetString("ConfigReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while saving config file.
        /// </summary>
        internal static string ConfigSaveError {
            get {
                return ResourceManager.GetString("ConfigSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Counting points..
        /// </summary>
        internal static string CountingPoints {
            get {
                return ResourceManager.GetString("CountingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done..
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID field is empty..
        /// </summary>
        internal static string EmptyIDField {
            get {
                return ResourceManager.GetString("EmptyIDField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Save at&quot; field is empty..
        /// </summary>
        internal static string EmptySaveAtField {
            get {
                return ResourceManager.GetString("EmptySaveAtField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eng {
            get {
                object obj = ResourceManager.GetObject("eng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while fetching games.
        /// </summary>
        internal static string ErrorFetchingGames {
            get {
                return ResourceManager.GetString("ErrorFetchingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while fetching players.
        /// </summary>
        internal static string ErrorFetchingPlayers {
            get {
                return ResourceManager.GetString("ErrorFetchingPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while parsing scores.
        /// </summary>
        internal static string ErrorParsingScores {
            get {
                return ResourceManager.GetString("ErrorParsingScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while saving text files.
        /// </summary>
        internal static string ErrorSavingTexts {
            get {
                return ResourceManager.GetString("ErrorSavingTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap esp {
            get {
                object obj = ResourceManager.GetObject("esp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fetching games..
        /// </summary>
        internal static string FetchingGames {
            get {
                return ResourceManager.GetString("FetchingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fetching list of players..
        /// </summary>
        internal static string FetchingPlayerList {
            get {
                return ResourceManager.GetString("FetchingPlayerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generating text files..
        /// </summary>
        internal static string GeneratingTextFiles {
            get {
                return ResourceManager.GetString("GeneratingTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Save at&quot; path is not valid: .
        /// </summary>
        internal static string NonValidPath {
            get {
                return ResourceManager.GetString("NonValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First match.
        /// </summary>
        internal static string OutputFirstMatch {
            get {
                return ResourceManager.GetString("OutputFirstMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last match VS:  {0}  ( {1} ).
        /// </summary>
        internal static string OutputLastMatch {
            get {
                return ResourceManager.GetString("OutputLastMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last victory VS:  {0}  ( {1} ).
        /// </summary>
        internal static string OutputLastVictory {
            get {
                return ResourceManager.GetString("OutputLastVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In Losers Bracket by:  {0}  ( {1} ).
        /// </summary>
        internal static string OutputLosersBy {
            get {
                return ResourceManager.GetString("OutputLosersBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player 1 Name.
        /// </summary>
        internal static string Player1Name {
            get {
                return ResourceManager.GetString("Player1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player 2 Name.
        /// </summary>
        internal static string Player2Name {
            get {
                return ResourceManager.GetString("Player2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player data.
        /// </summary>
        internal static string PlayerData {
            get {
                return ResourceManager.GetString("PlayerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while reading player data.
        /// </summary>
        internal static string PlayerDataReadError {
            get {
                return ResourceManager.GetString("PlayerDataReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didn&apos;t obtain any player. Check the ID..
        /// </summary>
        internal static string PlayersNotReceived {
            get {
                return ResourceManager.GetString("PlayersNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save at.
        /// </summary>
        internal static string SaveAt {
            get {
                return ResourceManager.GetString("SaveAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tournament stats.
        /// </summary>
        internal static string TournamentStats {
            get {
                return ResourceManager.GetString("TournamentStats", resourceCulture);
            }
        }
    }
}
